-- MySQL Script generated by MySQL Workbench
-- vie 10 feb 2017 17:32:57 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisaPeople
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema melisaPeople
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `melisaPeople` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `melisaPeople` ;

-- -----------------------------------------------------
-- Table `melisaPeople`.`pPhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pPhoneNumbers` (
  `id` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `number` VARCHAR(15) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pEmails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pEmails` (
  `id` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `email` VARCHAR(130) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  `idIdentityUpdated` CHAR(36) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pPeople`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pPeople` (
  `id` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `gender` TINYINT NOT NULL DEFAULT 1,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` CHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `name_INDEX` (`name` ASC),
  INDEX `lastName_INDEX` (`lastName` ASC),
  UNIQUE INDEX `name_lastName_UNIQUE` (`name` ASC, `lastName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pContacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pContacts` (
  `id` CHAR(36) NOT NULL,
  `idPeople` CHAR(36) NOT NULL,
  `idEmail` CHAR(36) NULL,
  `idPhoneNumber` CHAR(36) NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` CHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pContacts_pPhoneNumbers_idx` (`idEmail` ASC),
  INDEX `fk_pContacts_pEmails1_idx` (`idPhoneNumber` ASC),
  INDEX `fk_pContacts_pPeople1_idx` (`idPeople` ASC),
  CONSTRAINT `fk_pContacts_pPhoneNumbers`
    FOREIGN KEY (`idEmail`)
    REFERENCES `melisaPeople`.`pPhoneNumbers` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pContacts_pEmails1`
    FOREIGN KEY (`idPhoneNumber`)
    REFERENCES `melisaPeople`.`pEmails` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pContacts_pPeople1`
    FOREIGN KEY (`idPeople`)
    REFERENCES `melisaPeople`.`pPeople` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pLabelsContacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pLabelsContacts` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `key` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  INDEX `name_INDEX` (`name` ASC),
  INDEX `key_INDEX` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pContactsLabels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pContactsLabels` (
  `id` CHAR(36) NOT NULL,
  `idContact` CHAR(36) NOT NULL,
  `idLabelContact` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pContactsLabels_pContacts1_idx` (`idContact` ASC),
  INDEX `fk_pContactsLabels_pLabelsContacts1_idx` (`idLabelContact` ASC),
  CONSTRAINT `fk_pContactsLabels_pContacts1`
    FOREIGN KEY (`idContact`)
    REFERENCES `melisaPeople`.`pContacts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pContactsLabels_pLabelsContacts1`
    FOREIGN KEY (`idLabelContact`)
    REFERENCES `melisaPeople`.`pLabelsContacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pLabelsPhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pLabelsPhoneNumbers` (
  `id` SMALLINT NOT NULL,
  `name` VARCHAR(95) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `name_INDEX` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pContactsPhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pContactsPhoneNumbers` (
  `id` CHAR(36) NOT NULL,
  `idContact` CHAR(36) NOT NULL,
  `idPhoneNumber` CHAR(36) NOT NULL,
  `idLabelPhoneNumber` SMALLINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pContactsPhoneNumbers_pContacts1_idx` (`idContact` ASC),
  INDEX `fk_pContactsPhoneNumbers_pPhoneNumbers1_idx` (`idPhoneNumber` ASC),
  INDEX `fk_pContactsPhoneNumbers_pLabelsPhoneNumbers1_idx` (`idLabelPhoneNumber` ASC),
  CONSTRAINT `fk_pContactsPhoneNumbers_pContacts1`
    FOREIGN KEY (`idContact`)
    REFERENCES `melisaPeople`.`pContacts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pContactsPhoneNumbers_pPhoneNumbers1`
    FOREIGN KEY (`idPhoneNumber`)
    REFERENCES `melisaPeople`.`pPhoneNumbers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pContactsPhoneNumbers_pLabelsPhoneNumbers1`
    FOREIGN KEY (`idLabelPhoneNumber`)
    REFERENCES `melisaPeople`.`pLabelsPhoneNumbers` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pLabelsEmails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pLabelsEmails` (
  `id` SMALLINT NOT NULL,
  `name` VARCHAR(95) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `name_INDEX` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pContactsEmails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pContactsEmails` (
  `id` CHAR(36) NOT NULL,
  `idContact` CHAR(36) NOT NULL,
  `idEmail` CHAR(36) NOT NULL,
  `idLabelEmail` SMALLINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pContactsEmails_pContacts1_idx` (`idContact` ASC),
  INDEX `fk_pContactsEmails_pEmails1_idx` (`idEmail` ASC),
  INDEX `fk_pContactsEmails_pLabelsEmails1_idx` (`idLabelEmail` ASC),
  CONSTRAINT `fk_pContactsEmails_pContacts1`
    FOREIGN KEY (`idContact`)
    REFERENCES `melisaPeople`.`pContacts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pContactsEmails_pEmails1`
    FOREIGN KEY (`idEmail`)
    REFERENCES `melisaPeople`.`pEmails` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pContactsEmails_pLabelsEmails1`
    FOREIGN KEY (`idLabelEmail`)
    REFERENCES `melisaPeople`.`pLabelsEmails` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
