-- MySQL Script generated by MySQL Workbench
-- mié 15 feb 2017 10:56:53 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisaPeople
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema melisaPeople
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `melisaPeople` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `melisaPeople` ;

-- -----------------------------------------------------
-- Table `melisaPeople`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`people` (
  `id` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `sex` TINYINT NOT NULL DEFAULT 1,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` CHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `name_INDEX` (`name` ASC),
  INDEX `lastName_INDEX` (`lastName` ASC),
  UNIQUE INDEX `name_lastName_UNIQUE` (`name` ASC, `lastName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`labelsTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`labelsTypes` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`labels` (
  `id` CHAR(36) NOT NULL,
  `idLabelType` SMALLINT NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `name` VARCHAR(95) NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pLabels_pLabelsTypes1_idx` (`idLabelType` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  CONSTRAINT `fk_labels_labelsTypes1`
    FOREIGN KEY (`idLabelType`)
    REFERENCES `melisaPeople`.`labelsTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`peoplePhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`peoplePhoneNumbers` (
  `id` CHAR(36) NOT NULL,
  `idPeople` CHAR(36) NOT NULL,
  `idLabel` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `number` VARCHAR(15) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_peoplePhoneNumbers_people1_idx` (`idPeople` ASC),
  INDEX `fk_peoplePhoneNumbers_labels1_idx` (`idLabel` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  CONSTRAINT `fk_peoplePhoneNumbers_people1`
    FOREIGN KEY (`idPeople`)
    REFERENCES `melisaPeople`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peoplePhoneNumbers_labels1`
    FOREIGN KEY (`idLabel`)
    REFERENCES `melisaPeople`.`labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`pContactsLabels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`pContactsLabels` (
  `id` CHAR(36) NOT NULL,
  `idContact` CHAR(36) NOT NULL,
  `idLabelContact` SMALLINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`peopleEmails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`peopleEmails` (
  `id` CHAR(36) NOT NULL,
  `idPeople` CHAR(36) NOT NULL,
  `idLabel` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `email` VARCHAR(95) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` CHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_peopleEmails_people1_idx` (`idPeople` ASC),
  INDEX `fk_peopleEmails_labels1_idx` (`idLabel` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_peopleEmails_people1`
    FOREIGN KEY (`idPeople`)
    REFERENCES `melisaPeople`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peopleEmails_labels1`
    FOREIGN KEY (`idLabel`)
    REFERENCES `melisaPeople`.`labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
