-- MySQL Script generated by MySQL Workbench
-- jue 16 feb 2017 13:51:10 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisaPeople
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema melisaPeople
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `melisaPeople` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `melisaPeople` ;

-- -----------------------------------------------------
-- Table `melisaPeople`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`people` (
  `id` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `sex` TINYINT NOT NULL DEFAULT 1,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` CHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `name_INDEX` (`name` ASC),
  INDEX `lastName_INDEX` (`lastName` ASC),
  UNIQUE INDEX `name_lastName_UNIQUE` (`name` ASC, `lastName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`labelsTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`labelsTypes` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `name_INDEX` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`labels` (
  `id` CHAR(36) NOT NULL,
  `idLabelType` SMALLINT NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `name` VARCHAR(95) NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pLabels_pLabelsTypes1_idx` (`idLabelType` ASC),
  UNIQUE INDEX `idLabelType_name_UNIQUE` (`idLabelType` ASC, `name` ASC),
  UNIQUE INDEX `idLabelType_key_UNIQUE` (`idLabelType` ASC, `key` ASC),
  INDEX `idLabelType_name_INDEX` (`idLabelType` ASC, `name` ASC),
  CONSTRAINT `fk_labels_labelsTypes1`
    FOREIGN KEY (`idLabelType`)
    REFERENCES `melisaPeople`.`labelsTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`peoplePhoneNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`peoplePhoneNumbers` (
  `id` CHAR(36) NOT NULL,
  `idPeople` CHAR(36) NOT NULL,
  `idLabel` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `number` VARCHAR(15) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_peoplePhoneNumbers_people1_idx` (`idPeople` ASC),
  INDEX `fk_peoplePhoneNumbers_labels1_idx` (`idLabel` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  CONSTRAINT `fk_peoplePhoneNumbers_people1`
    FOREIGN KEY (`idPeople`)
    REFERENCES `melisaPeople`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peoplePhoneNumbers_labels1`
    FOREIGN KEY (`idLabel`)
    REFERENCES `melisaPeople`.`labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`peopleEmails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`peopleEmails` (
  `id` CHAR(36) NOT NULL,
  `idPeople` CHAR(36) NOT NULL,
  `idLabel` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `email` VARCHAR(95) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` CHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_peopleEmails_people1_idx` (`idPeople` ASC),
  INDEX `fk_peopleEmails_labels1_idx` (`idLabel` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_peopleEmails_people1`
    FOREIGN KEY (`idPeople`)
    REFERENCES `melisaPeople`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peopleEmails_labels1`
    FOREIGN KEY (`idLabel`)
    REFERENCES `melisaPeople`.`labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`peopleLabels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`peopleLabels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idPeople` CHAR(36) NOT NULL,
  `idLabel` CHAR(36) NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_peopleLabels_people1_idx` (`idPeople` ASC),
  INDEX `fk_peopleLabels_labels1_idx` (`idLabel` ASC),
  CONSTRAINT `fk_peopleLabels_people1`
    FOREIGN KEY (`idPeople`)
    REFERENCES `melisaPeople`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peopleLabels_labels1`
    FOREIGN KEY (`idLabel`)
    REFERENCES `melisaPeople`.`labels` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`states` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`municipalities` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `idState` SMALLINT NOT NULL,
  `name` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipalities_states1_idx` (`idState` ASC),
  UNIQUE INDEX `idState_name_UNIQUE` (`idState` ASC, `name` ASC),
  INDEX `idState_INDEX` (`idState` ASC),
  INDEX `idState_name_INDEX` (`idState` ASC, `name` ASC),
  CONSTRAINT `fk_municipalities_states1`
    FOREIGN KEY (`idState`)
    REFERENCES `melisaPeople`.`states` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisaPeople`.`peopleAddresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisaPeople`.`peopleAddresses` (
  `id` CHAR(36) NOT NULL,
  `idPeople` CHAR(36) NOT NULL,
  `idState` SMALLINT NOT NULL,
  `idMunicipality` SMALLINT NOT NULL,
  `idIdentityCreated` CHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` CHAR(36) NULL,
  `street` VARCHAR(150) NULL,
  `colony` VARCHAR(100) NULL,
  `postalCode` VARCHAR(45) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_peopleAddresses_people1_idx` (`idPeople` ASC),
  INDEX `fk_peopleAddresses_states1_idx` (`idState` ASC),
  INDEX `fk_peopleAddresses_municipalities1_idx` (`idMunicipality` ASC),
  CONSTRAINT `fk_peopleAddresses_people1`
    FOREIGN KEY (`idPeople`)
    REFERENCES `melisaPeople`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peopleAddresses_states1`
    FOREIGN KEY (`idState`)
    REFERENCES `melisaPeople`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peopleAddresses_municipalities1`
    FOREIGN KEY (`idMunicipality`)
    REFERENCES `melisaPeople`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
